[package]
name = "sci-punk/knit-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1"
Component = "sleitnick/component@2.4.5"
Maid = "quenty/maid@2.0.1-canary"
Janitor = "howmanysmall/janitor@^1.14.1"
Signal = "sleitnick/signal@1.1.0"
Option = "sleitnick/option@1.0.3"
Roact = "roblox/roact@^1.4.2"