local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RarityEnum = require(ReplicatedStorage.Source.Enums.RaritiesEnum)
local CurrenciesEnum = require(ReplicatedStorage.Source.Enums.CurrenciesEnum)
local emotes = {
	Club_Dance = {
		name = "Club Dance",
		animation = "rbxassetid://18374371611",
		defaultTempo = 1,
		rarity = RarityEnum.Common,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Boneless = {
		name = "Boneless",
		animation = "rbxassetid://18371130540",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Feet_Clap = {
		name = "Feet Clap",
		animation = "rbxassetid://18371159441",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 2_000,
		currency = CurrenciesEnum.BattleGems,
		forSale = true,
	},
	Sprinkling = {
		name = "Sprinkling",
		animation = "rbxassetid://18458982239",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 2_000,
		currency = CurrenciesEnum.BattleGems,
		forSale = true,
	},
	Bandit_Dance = {
		name = "Bandit Dance",
		animation = "rbxassetid://18448409876",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 2_000,
		currency = CurrenciesEnum.BattleGems,
		forSale = true,
	},
	Eagling = {
		name = "Eagling",
		animation = "rbxassetid://18451372412",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 2_000,
		currency = CurrenciesEnum.BattleGems,
		forSale = true,
	},
	Dab = {
		name = "Dab",
		animation = "rbxassetid://18368662048",
		defaultTempo = 1,
		rarity = RarityEnum.Common,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Cosita = {
		name = "Cosita",
		animation = "rbxassetid://18371179610",
		defaultTempo = 1,
		rarity = RarityEnum.Mythic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	The_Twist = {
		name = "The Twist",
		animation = "rbxassetid://14026838589",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Zombiller = {
		name = "Zombiller",
		animation = "rbxassetid://18371293680",
		defaultTempo = 1,
		rarity = RarityEnum.Mythic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Worming = {
		name = "Worming",
		animation = "rbxassetid://18370895598",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Hype = {
		name = "Hype",
		animation = "rbxassetid://18371116191",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Fresh = {
		name = "Fresh",
		animation = "rbxassetid://18372752865",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Take_The_L = {
		name = "Take The L",
		animation = "rbxassetid://14044815170",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	The_Robot = {
		name = "The Robot",
		animation = "rbxassetid://18522440380",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Did_it = {
		name = "Did it",
		animation = "rbxassetid://18370908061",
		defaultTempo = 1,
		rarity = RarityEnum.Mythic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Rider = {
		name = "Rider",
		animation = "rbxassetid://18373362284",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
},
	Slitherin = {
		name = "Slitherin",
		animation = "rbxassetid://18371429159",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Ballin = {
		name = "Ballin",
		animation = "rbxassetid://18371396778",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	["Flipping_&_Flexing"] = {
		name = "Flipping & Flexing",
		animation = "rbxassetid://18460020159",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Citrus_Grove = {
		name = "Citrus Grove",
		animation = "rbxassetid://18460486706",
		defaultTempo = 1,
		rarity = RarityEnum.Mythic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Head_Banger = {
		name = "Head Banger",
		animation = "rbxassetid://18476007469",
		defaultTempo = 1,
		rarity = RarityEnum.Mythic,
		price = 8_500,
		currency = CurrenciesEnum.BattleGems,
		forSale = true,
	},
	Macarena = {
		name = "Macarena",
		animation = "rbxassetid://18474124750",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Pumped = {
		name = "Pumped",
		animation = "rbxassetid://18498617766",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Shuffle = {
		name = "Shuffle",
		animation = "rbxassetid://18498927213",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Bring_It = {
		name = "Bring It",
		animation = "rbxassetid://18505593958",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Tear_Up = {
		name = "Tear Up",
		animation = "rbxassetid://18505620252",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Wild_Feet = {
		name = "Wild Feet",
		animation = "rbxassetid://18506664467",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Showslopper = {
		name = "Showslopper",
		animation = "rbxassetid://18506791178",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Yeet = {
		name = "Yeet",
		animation = "rbxassetid://18506915993",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Flowing = {
		name = "Flowing",
		animation = "rbxassetid://18507129898",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Classic_Dance = {
		name = "Classic Dance",
		animation = "rbxassetid://18507210516",
		defaultTempo = 1,
		rarity = RarityEnum.Common,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Side_To_Side = {
		name = "Side To Side",
		animation = "rbxassetid://18507534107",
		defaultTempo = 1,
		rarity = RarityEnum.Common,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Lock_It = {
		name = "Lock It",
		animation = "rbxassetid://18507742372",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Infinite_Dab = {
		name = "Infinite Dab",
		animation = "rbxassetid://18507890571",
		defaultTempo = 1,
		rarity = RarityEnum.Common,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	T_Pose = {
		name = "T-Pose",
		animation = "rbxassetid://18522748159",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Friendly_Dance = {
		name = "Friendly Dance",
		animation = "rbxassetid://18523877586",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
}

return emotes
