local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RarityEnum = require(ReplicatedStorage.Source.Enums.RaritiesEnum)
local CurrenciesEnum = require(ReplicatedStorage.Source.Enums.CurrenciesEnum)
local emotes = {
	Club_Dance = {
		name = "Club Dance",
		animation = "rbxassetid://18374371611",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	-- Sleep = {
	-- 	name = "Sleep",
	-- 	animation = "rbxassetid://5375125612",
	-- 	defaultTempo = 1,
	-- 	rarity = RarityEnum.Common,
	-- 	price = 200,
	-- 	currency = CurrenciesEnum.BattleCoins,
	-- 	forSale = true
	-- },
	Boneless = {
		name = "Boneless",
		animation = "rbxassetid://18371130540",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Feet_Clap = {
		name = "Feet Clap",
		animation = "rbxassetid://18371159441",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 2_000,
		currency = CurrenciesEnum.BattleGems,
		forSale = true,
	},
	Bandit_Dance = {
		name = "Bandit Dance",
		animation = "rbxassetid://18448409876",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 2_000,
		currency = CurrenciesEnum.BattleGems,
		forSale = true,
	},
	Eagling = {
		name = "Eagling",
		animation = "rbxassetid://18451372412",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 2_000,
		currency = CurrenciesEnum.BattleGems,
		forSale = true,
	},
	Dab = {
		name = "Dab",
		animation = "rbxassetid://18368662048",
		defaultTempo = 1,
		rarity = RarityEnum.Common,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Cosita = {
		name = "Cosita",
		animation = "rbxassetid://18371179610",
		defaultTempo = 1,
		rarity = RarityEnum.Mythic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	The_Twist = {
		name = "The Twist",
		animation = "rbxassetid://14026838589",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Zombiller = {
		name = "Zombiller",
		animation = "rbxassetid://18371293680",
		defaultTempo = 1,
		rarity = RarityEnum.Mythic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Worming = {
		name = "Worming",
		animation = "rbxassetid://18370895598",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Hype = {
		name = "Hype",
		animation = "rbxassetid://18371116191",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Fresh = {
		name = "Fresh",
		animation = "rbxassetid://18372752865",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Take_The_L = {
		name = "Take The L",
		animation = "rbxassetid://14044815170",
		defaultTempo = 1,
		rarity = RarityEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	The_Robot = {
		name = "The Robot",
		animation = "rbxassetid://18371388662",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Did_it = {
		name = "Did it",
		animation = "rbxassetid://18370908061",
		defaultTempo = 1,
		rarity = RarityEnum.Mythic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Rider = {
		name = "Rider",
		animation = "rbxassetid://18373362284",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Slitherin = {
		name = "Slitherin",
		animation = "rbxassetid://18371429159",
		defaultTempo = 1,
		rarity = RarityEnum.Epic,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Ballin = {
		name = "Ballin",
		animation = "rbxassetid://18371396778",
		defaultTempo = 1,
		rarity = RarityEnum.Rare,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
}

return emotes
