local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RaritiesEnum = require(ReplicatedStorage.Source.Enums.RaritiesEnum)
local CurrenciesEnum = require(ReplicatedStorage.Source.Enums.CurrenciesEnum)
local skins = {
	AlterEgo = {
		skinID = "rbxassetid://13643596771",
		rarity = RaritiesEnum.Rare,
		name = "Alter-Ego",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Venomus = {
		skinID = "rbxassetid://358113752",
		rarity = RaritiesEnum.Mythic,
		name = "Venomus",
		price = 6_000,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	AllSeeingEye = {
		skinID = "rbxassetid://358279560",
		rarity = RaritiesEnum.Mythic,
		name = "All-Seeing Eye",
		price = 3_300,
		currency = "BattleGems",
		forSale = true,
	},
	AbstractPeach = {
		skinID = "rbxassetid://13655041050",
		rarity = RaritiesEnum.Legendary,
		name = "Abstract Peach",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	RoyalOrnate = {
		skinID = "rbxassetid://13620123374",
		rarity = RaritiesEnum.Epic,
		name = "Royal Ornate",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Pineapple = {
		skinID = "rbxassetid://13655576502",
		rarity = RaritiesEnum.Common,
		name = "Pineapple",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Duckies = {
		skinID = "rbxassetid://358413518",
		rarity = RaritiesEnum.Common,
		name = "Duckies",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Totopos = {
		skinID = "rbxassetid://358284720",
		rarity = RaritiesEnum.Rare,
		name = "Totopos",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	DigitalDisturbance = {
		skinID = "rbxassetid://358113994",
		rarity = RaritiesEnum.Epic,
		name = "Digital Disturbance",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Connections = {
		skinID = "rbxassetid://358209640",
		rarity = RaritiesEnum.Epic,
		name = "Connections",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	PartyTime = {
		skinID = "rbxassetid://358113881",
		rarity = RaritiesEnum.Rare,
		name = "Party Time",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Cherries = {
		skinID = "rbxassetid://13662981938",
		rarity = RaritiesEnum.Common,
		name = "Cherries",
		price = 899,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Steampunk = {
		skinID = "rbxassetid://13663622687",
		rarity = RaritiesEnum.Rare,
		name = "Steampunk",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Darkness = {
		skinID = "rbxassetid://13664411385",
		rarity = RaritiesEnum.Common,
		name = "Darkness",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	VoidScars = {
		skinID = "rbxassetid://13664464931",
		rarity = RaritiesEnum.Legendary,
		name = "Void Scars",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Constellation = {
		skinID = "rbxassetid://13664532889",
		rarity = RaritiesEnum.Rare,
		name = "Constellation",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Bowies = {
		skinID = "rbxassetid://13664668442",
		rarity = RaritiesEnum.Common,
		name = "Bowies",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	IndustrialSpace = {
		skinID = "rbxassetid://13664822366",
		rarity = RaritiesEnum.Rare,
		name = "Industrial Space",
		price = 600,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	CoffinsSkulls = {
		skinID = "rbxassetid://13665000362",
		rarity = RaritiesEnum.Epic,
		name = "Coffins & Skulls",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	RainbowBats = {
		skinID = "rbxassetid://13664947705",
		rarity = RaritiesEnum.Rare,
		name = "Rainbow Bats",
		price = 2_000,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	SugarHaze = {
		skinID = "rbxassetid://13665979274",
		rarity = RaritiesEnum.Epic,
		name = "Sugar-Haze",
		price = 2_000,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	ForestCamo = {
		skinID = "rbxassetid://13666123351",
		rarity = RaritiesEnum.Common,
		name = "Forest Camo",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	SnowCamo = {
		skinID = "rbxassetid://13667523981",
		rarity = RaritiesEnum.Common,
		name = "Snow Camo",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	DesertCamo = {
		skinID = "rbxassetid://13667570547",
		rarity = RaritiesEnum.Common,
		name = "Desert Camo",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	SharkCamo = {
		skinID = "rbxassetid://13667632021",
		rarity = RaritiesEnum.Epic,
		name = "Shark Camo",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	PunkSpirit = {
		skinID = "rbxassetid://13667613116",
		rarity = RaritiesEnum.Legendary,
		name = "Punk Spirit",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	GhostCamo = {
		skinID = "rbxassetid://13667665573",
		rarity = RaritiesEnum.Legendary,
		name = "Ghost Camo",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Kraken = {
		skinID = "rbxassetid://390097022",
		rarity = RaritiesEnum.Mythic,
		name = "Kraken",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	MonkeyRage = {
		skinID = "rbxassetid://13667787552",
		rarity = RaritiesEnum.Legendary,
		name = "Monkey Rage",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Dragonfruits = {
		skinID = "rbxassetid://13667938944",
		rarity = RaritiesEnum.Rare,
		name = "Dragonfruits",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Melancoly = {
		skinID = "rbxassetid://13829565984",
		rarity = RaritiesEnum.Legendary,
		name = "Melancoly",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	MayanFigures = {
		skinID = "rbxassetid://13867946001",
		rarity = RaritiesEnum.Mythic,
		name = "Mayan Figures",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	SpiderSense = {
		skinID = "rbxassetid://13874149361",
		rarity = RaritiesEnum.Rare,
		name = "Spider Sense",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	SpiderSpirit = {
		skinID = "rbxassetid://13874336571",
		rarity = RaritiesEnum.Legendary,
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
		name = "Spider Spirit",
	},
	SkullRoses = {
		skinID = "rbxassetid://15021618982",
		rarity = RaritiesEnum.Epic,
		name = "Skull & Roses",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Tech = {
		skinID = "rbxassetid://15021666612",
		rarity = RaritiesEnum.Rare,
		name = "Tech",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Frost = {
		skinID = "rbxassetid://18476194546",
		rarity = RaritiesEnum.Rare,
		name = "Frost",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	AztecFigures = {
		skinID = "rbxassetid://18476218694",
		rarity = RaritiesEnum.Mythic,
		name = "Aztec Figures",
		price = 20_000,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	SkullsGuns = {
		skinID = "rbxassetid://18477496230",
		rarity = RaritiesEnum.Legendary,
		name = "Skulls & Guns",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Firy = {
		skinID = "rbxassetid://18478633391",
		rarity = RaritiesEnum.Epic,
		name = "Firy",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Explosive = {
		skinID = "rbxassetid://18478759465",
		rarity = RaritiesEnum.Legendary,
		name = "Explosive",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Radioactive = {
		skinID = "rbxassetid://18480140539",
		rarity = RaritiesEnum.Legendary,
		name = "Radioactive",
		price = 2_000,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Wooden = {
		skinID = "rbxassetid://18491480069",
		rarity = RaritiesEnum.Common,
		name = "Wooden",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Urban = {
		skinID = "rbxassetid://18491989241",
		rarity = RaritiesEnum.Rare,
		name = "Urban",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Moon = {
		skinID = "rbxassetid://18492130459",
		rarity = RaritiesEnum.Epic,
		name = "Moon",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Undead = {
		skinID = "rbxassetid://18494249959",
		rarity = RaritiesEnum.Epic,
		name = "Undead",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Fallout = {
		skinID = "rbxassetid://18509573915",
		rarity = RaritiesEnum.Legendary,
		name = "Fallout",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Magma = {
		skinID = "rbxassetid://18510130629",
		rarity = RaritiesEnum.Mythic,
		name = "Magma",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
		shouldAnimate = true,
	},
	Storm = {
		skinID = "rbxassetid://18513015259",
		rarity = RaritiesEnum.Legendary,
		name = "Storm",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Electric = {
		skinID = "rbxassetid://18513728036",
		rarity = RaritiesEnum.Mythic,
		name = "Electric",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Tiger = {
		skinID = "rbxassetid://18513771873",
		rarity = RaritiesEnum.Mythic,
		name = "Tiger",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Alien = {
		skinID = "rbxassetid://18513927777",
		rarity = RaritiesEnum.Rare,
		name = "Alien",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Fierce = {
		skinID = "rbxassetid://18525119301",
		rarity = RaritiesEnum.Mythic,
		name = "Fierce",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Vampire = {
		skinID = "rbxassetid://18539448958",
		rarity = RaritiesEnum.Mythic,
		name = "Vampire",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
		shouldAnimate = true,
	},
	Enigma = {
		skinID = "rbxassetid://18540437495",
		rarity = RaritiesEnum.Legendary,
		name = "Enigma",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
		shouldAnimate = true,
	},
	Cards = {
		skinID = "rbxassetid://18540505140",
		rarity = RaritiesEnum.Epic,
		name = "Cards",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
	},
	Slime = {
		skinID = "rbxassetid://18549827843",
		rarity = RaritiesEnum.Epic,
		name = "Slime",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
		shouldAnimate = true,
	},
	Neon = {
		skinID = "rbxassetid://18549827843",
		rarity = RaritiesEnum.Epic,
		name = "Neon",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = true,
		shouldAnimate = true,
	},
	Cubism = {
		skinID = "rbxassetid://18555061749",
		rarity = RaritiesEnum.Epic,
		name = "Cubism",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = false,
		shouldAnimate = true,
	},
	Spiderweb = {
		skinID = "rbxassetid://18555236183",
		rarity = RaritiesEnum.Rare,
		name = "Spiderweb",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = false,
	},
	Blueprint = {
		skinID = "rbxassetid://18556603104",
		rarity = RaritiesEnum.Rare,
		name = "Blueprint",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = false,
	},
	Gold = {
		skinID = "rbxassetid://18556854114",
		rarity = RaritiesEnum.Rare,
		name = "Gold",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = false,
		shouldAnimate = true,
	},
	MarbleGold = {
		skinID = "rbxassetid://18556957598",
		rarity = RaritiesEnum.Epic,
		name = "Marble & Gold",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = false,
	},
	Monster = {
		skinID = "rbxassetid://18581769379",
		rarity = RaritiesEnum.Epic,
		name = "Monster",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = false,
	},
	TidalWaves = {
		skinID = "rbxassetid://18584921575",
		rarity = RaritiesEnum.Epic,
		name = "Tidal Waves",
		price = 200,
		currency = CurrenciesEnum.BattleCoins,
		forSale = false,
		shouldAnimate = true,
	},
}

return skins
